// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ak2dZv0uXjdY4HcnHLOGwJPC5RFMDUQ',
    appId: '1:786004134673:web:cb97e30475556c02245ab0',
    messagingSenderId: '786004134673',
    projectId: 'alifsteelapp-dc142',
    authDomain: 'alifsteelapp-dc142.firebaseapp.com',
    storageBucket: 'alifsteelapp-dc142.firebasestorage.app',
    measurementId: 'G-1LGK3KWKBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9nRWS7tneV2PN-wQYxHkreqDUZAqJCc',
    appId: '1:786004134673:android:251dd18ef6bdf21e245ab0',
    messagingSenderId: '786004134673',
    projectId: 'alifsteelapp-dc142',
    storageBucket: 'alifsteelapp-dc142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowPM9xaPbQS8DxobkqYI0nGJv_bARkT0',
    appId: '1:786004134673:ios:31c544f171523a9a245ab0',
    messagingSenderId: '786004134673',
    projectId: 'alifsteelapp-dc142',
    storageBucket: 'alifsteelapp-dc142.firebasestorage.app',
    iosBundleId: 'com.example.alifSteelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCowPM9xaPbQS8DxobkqYI0nGJv_bARkT0',
    appId: '1:786004134673:ios:31c544f171523a9a245ab0',
    messagingSenderId: '786004134673',
    projectId: 'alifsteelapp-dc142',
    storageBucket: 'alifsteelapp-dc142.firebasestorage.app',
    iosBundleId: 'com.example.alifSteelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0ak2dZv0uXjdY4HcnHLOGwJPC5RFMDUQ',
    appId: '1:786004134673:web:ddb421291e5f264b245ab0',
    messagingSenderId: '786004134673',
    projectId: 'alifsteelapp-dc142',
    authDomain: 'alifsteelapp-dc142.firebaseapp.com',
    storageBucket: 'alifsteelapp-dc142.firebasestorage.app',
    measurementId: 'G-GXHLQ0JFGJ',
  );
}
